export const CONFIRM_ACCOUNT_1 = 'CONFIRM_ACCOUNT_1';
export const CONFIRM_ACCOUNT_2 = 'CONFIRM_ACCOUNT_2';
export const PASSWORD_RESET_1 = 'PASSWORD_RESET_1';
export const PASSWORD_RESET_2 = 'PASSWORD_RESET_2';
export const DELETE_ACCOUNT_1 = 'DELETE_ACCOUNT_1';
export const DELETE_ACCOUNT_2 = 'DELETE_ACCOUNT_2';
